# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('email', models.CharField(max_length=40, verbose_name='email')),
                ('phone', models.CharField(max_length=40, verbose_name='phone')),
            ],
        ),
    ]
